/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioPrintRouteImport } from './routes/studio/print'
import { Route as StudioCoursesIndexRouteImport } from './routes/studio/courses/index'
import { Route as StudioCoursesCourseIdIndexRouteImport } from './routes/studio/courses/$courseId/index'
import { Route as StudioCoursesCourseIdLessonsLessonIdRouteImport } from './routes/studio/courses/$courseId/lessons/$lessonId'

const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioPrintRoute = StudioPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioCoursesIndexRoute = StudioCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioCoursesCourseIdIndexRoute =
  StudioCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => StudioRouteRoute,
  } as any)
const StudioCoursesCourseIdLessonsLessonIdRoute =
  StudioCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => StudioRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/studio': typeof StudioRouteRouteWithChildren
  '/studio/print': typeof StudioPrintRoute
  '/': typeof publicIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/courses/': typeof StudioCoursesIndexRoute
  '/studio/courses/$courseId/': typeof StudioCoursesCourseIdIndexRoute
  '/studio/courses/$courseId/lessons/$lessonId': typeof StudioCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/studio/print': typeof StudioPrintRoute
  '/': typeof publicIndexRoute
  '/studio': typeof StudioIndexRoute
  '/studio/courses': typeof StudioCoursesIndexRoute
  '/studio/courses/$courseId': typeof StudioCoursesCourseIdIndexRoute
  '/studio/courses/$courseId/lessons/$lessonId': typeof StudioCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/studio': typeof StudioRouteRouteWithChildren
  '/studio/print': typeof StudioPrintRoute
  '/(public)/': typeof publicIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/courses/': typeof StudioCoursesIndexRoute
  '/studio/courses/$courseId/': typeof StudioCoursesCourseIdIndexRoute
  '/studio/courses/$courseId/lessons/$lessonId': typeof StudioCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/studio'
    | '/studio/print'
    | '/'
    | '/studio/'
    | '/studio/courses/'
    | '/studio/courses/$courseId/'
    | '/studio/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/studio/print'
    | '/'
    | '/studio'
    | '/studio/courses'
    | '/studio/courses/$courseId'
    | '/studio/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/studio'
    | '/studio/print'
    | '/(public)/'
    | '/studio/'
    | '/studio/courses/'
    | '/studio/courses/$courseId/'
    | '/studio/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/print': {
      id: '/studio/print'
      path: '/print'
      fullPath: '/studio/print'
      preLoaderRoute: typeof StudioPrintRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/courses/': {
      id: '/studio/courses/'
      path: '/courses'
      fullPath: '/studio/courses/'
      preLoaderRoute: typeof StudioCoursesIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/courses/$courseId/': {
      id: '/studio/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/studio/courses/$courseId/'
      preLoaderRoute: typeof StudioCoursesCourseIdIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/courses/$courseId/lessons/$lessonId': {
      id: '/studio/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/studio/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof StudioCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
  }
}

interface StudioRouteRouteChildren {
  StudioPrintRoute: typeof StudioPrintRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioCoursesIndexRoute: typeof StudioCoursesIndexRoute
  StudioCoursesCourseIdIndexRoute: typeof StudioCoursesCourseIdIndexRoute
  StudioCoursesCourseIdLessonsLessonIdRoute: typeof StudioCoursesCourseIdLessonsLessonIdRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioPrintRoute: StudioPrintRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioCoursesIndexRoute: StudioCoursesIndexRoute,
  StudioCoursesCourseIdIndexRoute: StudioCoursesCourseIdIndexRoute,
  StudioCoursesCourseIdLessonsLessonIdRoute:
    StudioCoursesCourseIdLessonsLessonIdRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StudioRouteRoute: StudioRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
