/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'

const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/studio': typeof StudioRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/studio': typeof StudioRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/studio' | '/' | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio'
  id: '__root__' | '/studio' | '/(public)/' | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
  }
}

interface StudioRouteRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StudioRouteRoute: StudioRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
